name: Azure Static Web App CI/CD

on:
  push:
    branches:
      - master

env:
  NG_APP_BLOB_ENDPOINT: ${{ secrets.NG_APP_BLOB_ENDPOINT }}
  NG_APP_BLOB_ENDPOINT_PUBLIC: ${{ secrets.NG_APP_BLOB_ENDPOINT_PUBLIC }}
  NG_APP_COSMOS_ENDPOINT: ${{ secrets.NG_APP_COSMOS_ENDPOINT }}
  NG_APP_COSMOS_KEY: ${{ secrets.NG_APP_COSMOS_KEY }}
  NG_APP_GOOGLE_CLIENT_ID: ${{ secrets.NG_APP_GOOGLE_CLIENT_ID }}
  NG_APP_GITHUB_CLIENT_ID: ${{ secrets.NG_APP_GITHUB_CLIENT_ID }}
  NG_APP_MICROSOFT_CLIENT_ID: ${{ secrets.NG_APP_MICROSOFT_CLIENT_ID }}
  NG_APP_DISCORD_CLIENT_ID: ${{ secrets.NG_APP_DISCORD_CLIENT_ID }}
  NG_APP_BACKEND_ENDPOINT: ${{ secrets.NG_APP_BACKEND_ENDPOINT }}
  NG_APP_GA_TRACKING_ID: ${{ secrets.NG_APP_GA_TRACKING_ID }}
  NG_APP_ADMIN_EMAIL: ${{ secrets.NG_APP_ADMIN_EMAIL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.deployment_token }}
          action: 'upload'
          skip_app_build: true
          app_location: '/'
          api_location: ''
          output_location: ''
        env:
          VERSION: ${{ github.sha }}

